[build-system]
requires = ["setuptools", "wheel", "conan", "scikit-build>=0.11.1", "ninja"]
#conan has an older distro req than scikit-build, so specify conan first to get the correct version
# scikit version required for this https://github.com/scikit-build/scikit-build/issues/488